#!/usr/bin/env python

import sys

def factorize(num):
    factors = []
    for i in range(2, int(num**0.5) + 1):
        while num % i == 0:
            factors.append(i)
            num //= i
    if num > 1:
        factors.append(num)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename, 'r') as f:
        numbers = f.readlines()

    for num in numbers:
        num = int(num.strip())
        factors = factorize(num)
        print("{}={}*{}".format(num, factors[0], num//factors[0]))

if __name__ == "__main__":
    main()

